set(V ~/)
message(">Level 0: ${V}")
block()
  set(V ~/Modern_CMake_notes/)
  message(" >Level 1: ${V}")
    block()
    set(V ~/Modern_CMake_notes/minimum_notes/)
    message("  >Level 2: ${V}")
      block()
      set(V ~/Modern_CMake_notes/minimum_notes/02_Chapter/)
      message("   >Level 3: ${V}")
        block()
        set(V ~/Modern_CMake_notes/minimum_notes/02_Chapter/05_Scope)
        message("    >Level 4: ${V}")
          block()
          set(V ~/Modern_CMake_notes/minimum_notes/02_Chapter/05_Scope/Foo.txt)
          message("     >Level 5: ${V}")
          set(V ~/Modern_CMake_notes/minimum_notes/02_Chapter/05_Scope/Bar.txt)
          message("     >Level 5: ${V}")
          set(V ~/Modern_CMake_notes/minimum_notes/02_Chapter/05_Scope/Par.txt)
          message("     >Level 5: ${V}")
          set(V ~/Modern_CMake_notes/minimum_notes/02_Chapter/05_Scope/Zar.txt)
          message("     >Level 5: ${V}")
          set(V ~/Modern_CMake_notes/minimum_notes/02_Chapter/05_Scope/Var.txt)
          message("     >Level 5: ${V}")
        endblock()
        message("    >Level 4: ${V}")
      endblock()
      message("   >Level 3: ${V}")
    endblock()
    message("  >Level 2: ${V}")
  endblock()
  message(" >Level 1: ${V}")
endblock()
message(">Level 0: ${V}")

